server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

dubbo:
  scan:
    basePackages: com.jt    #开启包扫描
  application:
    name: consumer-web     #定义服务名称
  registry:                 #链接注册中心
    address: zookeeper://192.168.19.139:2181?backup=192.168.19.139:2182,192.168.19.139:2183
